### ISSUE TITLE
Can you make it available on windows?

### ISSUE THREAD

**Issue by skyborgff** [dbohdan/s2png#2]
Title explains all.

**Comment by dbohdan** [comment]
Here is a basic MSYS2-based build. I haven't tried to prune any of the DLL dependencies.

[s2png-0.7.0-bcbf395-msys2-win32.zip](https://github.com/dbohdan/s2png/files/661775/s2png-0.7.0-bcbf395-msys2-win32.zip)

Tell me if works on your machine.

**Comment by skyborgff** [comment]
It opens and immediately closes
Would't it be easier to make it based on this?
http://lifehacker.com/207905/hide-files-in-jpeg-images

**Comment by dbohdan** [comment]
>It opens and immediately closes

It's a command line program. You need to extract the archive somewhere and run `s2png.exe` from `cmd.exe`.

>Could't you make it based on this?
>http://lifehacker.com/207905/hide-files-in-jpeg-images

I don't quite understand what you mean but this program operates under a different principle.

**Comment by skyborgff** [comment]
It did worked. Do you need me to test something in specific. I encripted, and decripted a file (my mouse config) and it (seemed to be ) flawless.

Forget the link to the guide. this is much better.

> I haven't tried to prune any of the DLL dependencies.

You mean "compacting" (or making it installable i guess) it so the dll aren't wondering around right?

**Comment by dbohdan** [comment]
>It did worked. Do you need me to test something in specific. I encripted, and decripted a file (my mouse config) and it (seemed to be ) flawless.

Great! No need to test anything else.

>You mean "compacting" (or making it installable i guess) it so the dll aren't wondering around right?

I'll look into that for the next release. I plan on attaching a Windows binary to it.

**Comment by skyborgff** [comment]
If it works, why isn't it available to download on the main page? or are you making that right now?

BTW, i found this program on the steam reddit https://www.reddit.com/r/Steam/comments/5j5zk3/how_to_store_any_kind_of_file_on_steam_mp3_zip_exe/

**Comment by dbohdan** [comment]
As I said, I plan on attaching it to the next release (either v0.7.1 or v0.8.0), which will be available on the [releases page](https://github.com/dbohdan/s2png/releases). I can't tell you exactly when it will be done but I'll comment on this issue when it is.

**Comment by skyborgff** [comment]
Thank you very much. Keep up the great work :)

**Comment by dbohdan** [comment]
Thanks!

**Comment by dbohdan** [comment]
Actually, no need to wait for a release. I made it so that an executable is built and packaged for every commit (i.e., every change I make). Check out the link at the bottom of the [Windows section](https://github.com/dbohdan/s2png#windows).
